### PR TITLE
fix: use `hostname` as `display` default in `production` profile

### LINKED ISSUE #227: Do not enforce provisioning `display` config in production mode
### Description

When running UniCore in production mode, the `display` config is enforced.
This should be less strict, so it can be changed during runtime if it's not provided.
If provided through the config, it should not be able to be changed during runtime.

```
thread 'main' panicked at agent_shared/src/config/mod.rs:47:33:
Configuration is not suitable for production: `display` must be provided
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Motivation

_No response_

### Resources

_No response_

### To-do List

n/a

### PR DESCRIPTION
**Pull request by nanderstabel**
# Description of change
These changes use the `application_url` value as a sensible default for the applications display name. This ensures that the agent can be booted without the need to configure the display name/logo.

closes https://github.com/impierce/ssi-agent/issues/227

## Links to any relevant issues
- https://github.com/impierce/ssi-agent/issues/227

## How the change has been tested
Manually tested using Postman and UniMe.

## Definition of Done checklist
Add an `x` to the boxes that are relevant to your changes.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] I have successfully tested this change in a docker environment

### CODE REVIEW

File: agent_identity/src/state.rs [hunk 1]
```diff
@@ -121,9 +121,17 @@ pub async fn initialize(state: &IdentityState) -> anyhow::Result<()> {
 pub async fn query_profile(state: &IdentityState) -> Result<(), PersistenceError> {
     match query_handler(PROFILE_ID, &state.query.profile).await? {
         Some(Profile { display_name, logo, .. }) => {
-            if let Some(display) = config_mut().display.first_mut() {
+            let application_url = config().application_url.to_string();
```
Comment (daniel-mader) [inline agent_identity/src/state.rs]: Should we just use the hostname (domain) instead of the full URL (including the scheme, such as `https://`)?

**Review by daniel-mader — APPROVED** [review]
